apiVersion: apps/v1
kind: Deployment
metadata:
  name: vms-backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vms-backend
  template:
    metadata:
      labels:
        app: vms-backend
    spec:
      containers:
        - name: vms-backend
          image: neozhixuan/vms-backend:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: vms-backend-service
spec:
  selector:
    app: vms-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer # Use NodePort if LoadBalancer is not supported
